### ISSUE TITLE
Incompatibility issue with markdown-it-footnote 

### ISSUE THREAD

**Issue by ParaN3xus** [Cerallin/hexo-theme-yuzu#16]
When using footnotes, the footnote content is wrapping to a new line after the number.

Here's a demo: http://localhost:4000/2023/09/16/cpp-identifiers-with-unicode-char/

**Comment by Cerallin** [comment]
Please post a piece of markdown code. We cannot access your "localhost".

**Comment by ParaN3xus** [comment]
Sorry
https://paran3xus.github.io/2023/09/16/cpp-identifiers-with-unicode-char/
https://gist.github.com/ParaN3xus/855ace1e13000d54dee7039e4452e7d5
