### ISSUE TITLE
无法正确设置左侧menu😭😭😭

### ISSUE THREAD

**Issue by oooooomyxxx** [Cerallin/hexo-theme-yuzu#2]
你好
![](https://s2.loli.net/2022/03/18/djMT9oRkLeh8zOn.png)
我按照你md中”将 config.yml 中 theme 字段改为 hexo-theme-yuzu，在 config.yml 中添加如下内容：“
在这张图片中点击左侧分类按钮”芳香”，无法出现含有“categories：芳香”的链接
弄了半天，也没不好，无法自动生成分类页面？
无法像你在notes.cerallin.top左侧中，点击“计算机与通信工程”，就能出现所有分类为计算机与通信工程的所有文章
![](https://s2.loli.net/2022/03/18/KABTdO4R8x2jwQM.png)
你是如何设置的？

**Comment by Cerallin** [comment]
![image](https://user-images.githubusercontent.com/66366855/159111623-4d7a82a4-aaf3-4ca2-bdb9-dd4b6c6f424f.png)

如图所示，在meta信息里有一个categories字段~

**Comment by oooooomyxxx** [comment]
只改了meta里categories字段的名字，但是页面显示404😭😭😭

**Comment by oooooomyxxx** [comment]
![image](https://user-images.githubusercontent.com/85954555/161873778-def0f12e-6016-405b-825c-e8b6799a383b.png)
就是点击Post1或Post2之后，显示如图
![image](https://user-images.githubusercontent.com/85954555/161873933-679ddaec-71c0-4bc5-b8e8-26fc1556b081.png)
无法生成分类页面，
蟹蟹了！😭😭❤️

**Comment by Cerallin** [comment]
在根目录下的 `_config.yml` 里，你需要把 `your-link` 改成 `Post2`，或者说，要与这个分类的标题一致~

**Comment by oooooomyxxx** [comment]
![image](https://user-images.githubusercontent.com/85954555/161991862-1a8d99c5-ab90-498b-bb42-42268eb3ab9f.png)
只改这里不起作用❤️

**Comment by oooooomyxxx** [comment]
可以给个联系方式吗，找了别的主题还是不满意，🦀🦀

**Comment by DomeenoH** [comment]
> ![image](https://user-images.githubusercontent.com/85954555/161991862-1a8d99c5-ab90-498b-bb42-42268eb3ab9f.png) 只改这里不起作用❤️

这里配置中的意义是这样的

```
menu:
	分类名字:  #显示在首页侧边栏中的名字
		name: cate_name #url和文章front-matter中的目录名
		widget: Posts
		link: /categories/cate_name #这里和name中是一样的
```

如果要在这里的目录中添加文章，在文章的front-matter里加上目录参数就可以了

```
---
title: xxx
tags:
  - xxx
categories: cate_name
date: xxx
---
```

**Comment by oooooomyxxx** [comment]
> 

问题已解决，❤❤❤
