### ISSUE TITLE
Website display issue on Firefox

### ISSUE THREAD

**Issue by ParaN3xus** [Cerallin/hexo-theme-yuzu#20]
Created a new Hexo blog and followed the steps in the README.md to install the theme, but it's not displaying correctly. However, the example website in the README.md is displaying properly.

Firefox version: 117.0.1
hexo-theme-yuzu version: v3.2.1
Result of `hexo version`:
```
hexo: 6.3.0
hexo-cli: 4.3.1
os: linux 4.4.0-22621-Microsoft Debian GNU/Linux 11 (bullseye) 11 (bullseye)
node: 18.17.0
acorn: 8.8.2
ada: 2.5.0
ares: 1.19.1
brotli: 1.0.9
cldr: 43.0
icu: 73.1
llhttp: 6.0.11
modules: 108
napi: 9
nghttp2: 1.52.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.9+quic
simdutf: 3.2.12
tz: 2023c
undici: 5.22.1
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.18
v8: 10.2.154.26-node.26
zlib: 1.2.13.1-motley
```

![Snipaste_2023-09-23_11-09-04](https://github.com/Cerallin/hexo-theme-yuzu/assets/136563585/e1791fa6-e41f-4380-91e6-a10b89ea8ed5)

**Comment by Cerallin** [comment]
I've checked the MDN doc for `:has()` selector, and found it is not compatible with Firefox browsers, unless user enable it themselves.

I may come up with a solution later.

Ref: https://developer.mozilla.org/docs/Web/CSS/:has#browser_compatibility

**Comment by ParaN3xus** [comment]
Thank you!
