### ISSUE TITLE
自定义侧边栏显示异常

### ISSUE THREAD

**Issue by GrassBlock1** [Cerallin/hexo-theme-yuzu#21]
在 Firefox 119.0b6 下进行测试，配置为默认配置。
![截图 2023-10-19 12-12-23](https://github.com/Cerallin/hexo-theme-yuzu/assets/46253950/c827c8f4-6423-44dd-9460-afd07de9c41e)

相关配置：
https://paste.o3o.studio/?cf588a6a549020fd#9sRW9cgZMC6G3oyyhhKtdrbz12ioToH1PZGUkEPpeSXv

**Comment by Cerallin** [comment]
只有Firefox有问题的话，我晚上看看

**Comment by GrassBlock1** [comment]
> 只有Firefox有问题的话，我晚上看看

我测试了一下 edge 120.0.2165.1 dev (64 位)，也有这个问题...

**Comment by Cerallin** [comment]
@GrassBlock1 我新建了一个hexo项目，但是无法复现……请尝试一下`hexo clean`清除缓存之后重新生成。

**Comment by GrassBlock1** [comment]
> @GrassBlock1 我新建了一个hexo项目，但是无法复现……请尝试一下`hexo clean`清除缓存之后重新生成。

清除缓存试了一下，问题仍然存在...

**Comment by GrassBlock1** [comment]
> @GrassBlock1 我新建了一个hexo项目，但是无法复现……请尝试一下`hexo clean`清除缓存之后重新生成。

我尝试把 `.menubar-head` 的CSS display属性改成 `content` 能显示，但是看起来很奇怪：
![图片](https://github.com/Cerallin/hexo-theme-yuzu/assets/46253950/1c21700b-0972-44e5-8a56-47473376271c)

**Comment by GrassBlock1** [comment]
@Cerallin 所以想问一下，这个 menubar 是不是只在移动端展示？
我怀疑自己可能是之前fork主题的时候不小心在原分支下修改了相关的部分...

**Comment by Cerallin** [comment]
> @Cerallin 所以想问一下，这个 menubar 是不是只在移动端展示？ 

是的，移动端的 menubar 在 `layout/_partial/menubar.pug`，在 PC 端是隐藏的；PC 端的 header 在 `layout/_partial/header.pug`

**Comment by GrassBlock1** [comment]
> > 所以想问一下，这个 menubar 是不是只在移动端展示？
> 
> 是的，移动端的 menubar 在 `layout/_partial/menubar.pug`，在 PC 端是隐藏的；PC 端的 header 在 `layout/_partial/header.pug`
了解了，问题似乎在重新克隆主题后解决。
