### ISSUE TITLE
TOC可否有侧边模式😭

### ISSUE THREAD

**Issue by Candlest** [Cerallin/hexo-theme-yuzu#4]
感觉在最上面的**TOC**利用率不是很高（
文章页面侧面空出好大一块，**TOC**能实现侧边模式吗🥺

**Comment by Cerallin** [comment]
可以有。

好久之前TOC是在右侧的。出于（我忘了）的原因现在它只在中间，但现在我认为电脑端的TOC挪到旁边去更好。

在我没上传相关代码的时候欢迎PR.
