### ISSUE TITLE
可不可以对接个评论

### ISSUE THREAD

**Issue by novohit** [Cerallin/hexo-theme-yuzu#5]

**Comment by Cerallin** [comment]
@novohit 你好，我新建了一个分支麻烦你测试一下，相关配置在主题文件的`_config.yml`里。Valine的配置项见[官方文档](https://valine.js.org/configuration.html)，你看看有没有还想自定义的项。

附相关git指令：
```bash
# 如果你没有执行过git clone
git clone --branch feat/comments https://github.com/Cerallin/hexo-theme-yuzu
# 如果你已经执行过git clone
git fetch
git switch feat/comments
```

**Comment by novohit** [comment]
![Snipaste_2023-06-29_09-06-08](https://zwx-images-1305338888.cos.ap-guangzhou.myqcloud.com/typora/Snipaste_2023-06-29_09-06-08.png)
![Snipaste_2023-06-29_09-06-19](https://zwx-images-1305338888.cos.ap-guangzhou.myqcloud.com/typora/Snipaste_2023-06-29_09-06-19.png)

@Cerallin 你好，我测试是可以的，但是我看Valine配置里没字体大小的选项，评论这字体可能有点大

**Comment by Cerallin** [comment]
> @Cerallin 你好，我测试是可以的，但是我看Valine配置里没字体大小的选项，评论这字体可能有点大

修改已经提交，看看~

这次你只需要`git pull`就可以了。

**Comment by novohit** [comment]
> > @Cerallin 你好，我测试是可以的，但是我看Valine配置里没字体大小的选项，评论这字体可能有点大
> 
> 修改已经提交，看看~
> 
> 这次你只需要`git pull`就可以了。

好像字体大小没啥区别

**Comment by Cerallin** [comment]
> > > @Cerallin 你好，我测试是可以的，但是我看Valine配置里没字体大小的选项，评论这字体可能有点大
> > 
> > 
> > 修改已经提交，看看~
> > 这次你只需要`git pull`就可以了。
> 
> 好像字体大小没啥区别

这次我自己申了个LeenCloud账号，已经测试好了。请使用master分支测试~
