### ISSUE TITLE
如何改变主题缩进

### ISSUE THREAD

**Issue by MRLEEBLO** [Cerallin/hexo-theme-yuzu#8]
helpers.md里内容有点不具体，对于知识少的人不太友好。更改了global.styl中的Text indent后没有作用。
![uTools_1688143156359](https://github.com/Cerallin/hexo-theme-yuzu/assets/137767483/be261ff8-3f33-479c-9674-b313d1aaf6d3)

**Comment by Cerallin** [comment]
如果你是指全局缩进的话，目前没有提供选项。不过可以有

**Comment by MRLEEBLO** [comment]
所以现在是无法改变在正文中的默认缩进吗？

**Comment by novohit** [comment]
> 所以现在是无法改变在正文中的默认缩进吗？ 我还在博客中发现了另一个问题，不知道是不是自动缩进导致的（如附图）： 渲染后用列表语法书写的句子会自动换行 ![uTools_1688198732261](https://user-images.githubusercontent.com/137767483/250258553-efd964b1-edde-4207-9676-a3704dd1b5b1.png)

这个我也发现了
md 原生语法中每个列表之间不用有换行就行了，例如
-- first
-- second
-- third

**Comment by Cerallin** [comment]
> 所以现在是无法改变在正文中的默认缩进吗？

我已经提交了相关代码，master分支和v2.x都可以指定缩进了

**Comment by Cerallin** [comment]
有关列表的显示问题请移步 #9，每个issue应描述一个问题。

一个人多开几个issue也不要紧的（
