### ISSUE TITLE
无序列表（ul li）无法正常渲染

### ISSUE THREAD

**Issue by Cerallin** [Cerallin/hexo-theme-yuzu#9]
需要提供使用的markdown renderer (e.g. `hexo-renderer-marked`) 、**测试用例**和**当前版本**。

**Comment by MRLEEBLO** [comment]
markdown renderer: hexo-renderer-marked
测试用例：
![250258553-efd964b1-edde-4207-9676-a3704dd1b5b1](https://github.com/Cerallin/hexo-theme-yuzu/assets/137767483/b4f22398-26d0-45b2-ac1e-c4446512eca7)
当前主题版本：2.5
当前Hexo版本：6.3.0

**Comment by Cerallin** [comment]
> 测试用例：
> 
> ![250258553-efd964b1-edde-4207-9676-a3704dd1b5b1](https://github.com/Cerallin/hexo-theme-yuzu/assets/137767483/b4f22398-26d0-45b2-ac1e-c4446512eca7)

还请提供一下相关markdown代码

**Comment by MRLEEBLO** [comment]
> > 测试用例：
> > ![250258553-efd964b1-edde-4207-9676-a3704dd1b5b1](https://user-images.githubusercontent.com/137767483/250328731-b4f22398-26d0-45b2-ac1e-c4446512eca7.png)
> 
> 还请提供一下相关markdown代码

原代码：
> 打分区：
> \- \*\*Grade: 9+\*\* 
> \- \*\*Best: Dark Fantasy / Power / All of the Lights / Monster / Devil In a New Dress / Runaway\*\*
> \- \*\*Worst: None\*\*

**Comment by Cerallin** [comment]
@MRLEEBLO 我提交了相关代码，请试一试~
